[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build",
  "cp -r .next/static .next/standalone/.next/",
  "cp -r public .next/standalone/"
]

[start]
cmd = "node .next/standalone/server.js"
